dog_colors = {
        '1': "Apricot / Beige",
        '2': "Bicolor",
        '3': "Black",
        '4': "Brindle",
        '5': "Brown / Chocolate",
        '6': "Golden",
        '7': "Gray / Blue / Silver",
        '8': "Harlequin",
        '9': "Merle (Blue)",
        '10': "Merle (Red)",
        '11': "Red / Chestnut / Orange",
        '12': "Sable",
        '13': "Tricolor (Brown, Black, & White)",
        '14': "White / Cream",
        '15': "Yellow / Tan / Blond / Fawn"}

cat_colors = {
    '1': 'Black',
    '2': 'Black & White / Tuxedo',
    '3': 'Blue Cream',
    '4': 'Brown / Chocolate',
    '5': 'Buff & White',
    '6': 'Buff / Tan / Fawn',
    '7': 'Calico',
    '8': 'Chocolate Point',
    '9': 'Cream / Ivory',
    '10': 'Cream Point',
    '11': 'Dilute Calico',
    '12': 'Dilute Tortoiseshell',
    '13': 'Flame Point',
    '14': 'Gray & White',
    '15': 'Gray / Blue / Silver',
    '16': 'Lilac Point',
    '17': 'Orange & White',
    '18': 'Orange / Red',
    '19': 'Seal Point',
    '20': 'Smoke',
    '21': 'Tabby (Brown / Chocolate)',
    '22': 'Tabby (Buff / Tan / Fawn)',
    '23': 'Tabby (Gray / Blue / Silver)',
    '24': 'Tabby (Leopard / Spotted)',
    '25': 'Tabby (Orange / Red)',
    '26': 'Tabby (Tiger Striped)',
    '27': 'Torbie',
    '28': 'Tortoiseshell',
    '29': 'White',
    '30': 'Blue Point'
}
